version: "3"
services:
  #  Create a service named db.
  db:
    image: "postgres:12-alpine"
    container_name: "pipeline_db"
    #   Setup the username, password, and database name
    environment:
      - POSTGRES_USER=pipeline
      - POSTGRES_PASSWORD=pipeline
      - POSTGRES_DB=pipeline
    #   Map port 6432 (localhost) to port 5432 on the container
    ports:
      - "6432:5432"

  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    environment:
      GITLAB_OMNIBUS_CONFIG: |
       external_url 'http://localhost:9080'
       nginx['listen_port'] = 9080                   # make nginx to listen on the same port as confgured in external_url
       # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - '9080:9080'
      - '9443:443'
      - '9022:22'
    volumes:
      - '/srv/gitlab/config:/etc/gitlab'
      - '/srv/gitlab/logs:/var/log/gitlab'
      - '/srv/gitlab/data:/var/opt/gitlab'
