version: '3'
services:
  postgres:
    image: "postgres"
    container_name: "postgres"
    environment:
      POSTGRES_USER: ${CMWL_DB_USER}
      POSTGRES_PASSWORD: ${CMWL_DB_PASSWORD}
      POSTGRES_DB: ${CMWL_DB_NAME}
      PG_DATA: /var/lib/postgresql/data/pgdata
    ports:
      - "${CMWL_DB_PORT_NUMBER}:5432"
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
    restart: always

  mongo:
    image: "mongo"
    container_name: "mongo"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${CMWL_MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${CMWL_MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${CMWL_MONGO_DB}
    ports:
      - "${CMWL_MONGO_PORT}:27017"
    volumes:
      - ./docker/mongo:/data/db
    restart: always

  cmwl_pipeline:
    image: "cmwl_pipeline:0.1"
    environment:
      CMWL_PIPELINE_CONTAINER_PATH: ${CMWL_PIPELINE_CONTAINER_PATH}
      CMWL_PIPELINE_CONTAINER_NAME: ${CMWL_PIPELINE_CONTAINER_NAME}
      CMWL_PIPELINE_CONTAINER_LOGS: ${CMWL_PIPELINE_CONTAINER_LOGS}
      CMWL_DB_SERVER_NAME: ${CMWL_DB_SERVER_NAME}
      CMWL_DB_PORT_NUMBER: ${CMWL_DB_PORT_NUMBER}
      CMWL_DB_NAME: ${CMWL_DB_NAME}
      CMWL_DB_USER: ${CMWL_DB_USER}
      CMWL_DB_PASSWORD: ${CMWL_DB_PASSWORD}
      CMWL_MONGO_USER: ${CMWL_MONGO_USER}
      CMWL_MONGO_PASSWORD: ${CMWL_MONGO_PASSWORD}
      CMWL_MONGO_HOST: ${CMWL_MONGO_HOST}
      CMWL_MONGO_PORT: ${CMWL_MONGO_PORT}
      CMWL_MONGO_AUTH: ${CMWL_MONGO_AUTH}
      CMWL_MONGO_DB: ${CMWL_MONGO_DB}
      CMWL_MONGO_COLLECTION: ${CMWL_MONGO_COLLECTION}
      CMWL_GITLAB_TOKEN: ${CMWL_GITLAB_TOKEN}
      CMWL_GITLAB_URL: ${CMWL_GITLAB_URL}
    ports:
      - "${CMWL_PIPELINE_CONTAINER_PORT}:8080"

  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    environment:
      GITLAB_OMNIBUS_CONFIG: |
       external_url 'http://localhost:9080'
       nginx['listen_port'] = 9080                   # make nginx to listen on the same port as confgured in external_url
       # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - '9080:9080'
      - '9443:443'
      - '9022:22'
    volumes:
      - ./docker/gitlab/config:/etc/gitlab
      - ./docker/gitlab/logs:/var/log/gitlab
      - ./docker/gitlab/data:/var/opt/gitlab
