version: '3'
services:
  postgres:
    image: "postgres"
    container_name: "postgres"
    environment:
      POSTGRES_USER: ${CMWL_DB_USER}
      POSTGRES_PASSWORD: ${CMWL_DB_PASSWORD}
      POSTGRES_DB: ${CMWL_DB_NAME}
      PG_DATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
    restart: always

  mongo:
    image: "mongo"
    container_name: "mongo"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${CMWL_MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${CMWL_MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${CMWL_MONGO_DB}
    ports:
      - "27017:27017"
    volumes:
      - ./docker/mongo:/data/db
    restart: always

  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    environment:
      GITLAB_OMNIBUS_CONFIG: |
       external_url 'http://localhost:9080'
       nginx['listen_port'] = 9080                   # make nginx to listen on the same port as confgured in external_url
       # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - '9080:9080'
      - '9443:443'
      - '9022:22'
    volumes:
      - '/srv/gitlab/config:/etc/gitlab'
      - '/srv/gitlab/logs:/var/log/gitlab'
      - '/srv/gitlab/data:/var/opt/gitlab'
