#!/usr/bin/env bash

script_dir=$(dirname "${0}")
hook_name=$(basename "${0}")

hook_dir="${script_dir}/${hook_name}.d"

if [[ -d ${hook_dir} ]]; then
  for hook in "${hook_dir}"/*; do
    "${hook}" "${@}"
    exit_code=${?}

    if [ ${exit_code} != 0 ]; then
      error=$(tput setaf 1)
      normal=$(tput sgr0)
      script_name=$(basename "${hook}")
      echo "${error}Hook ${hook_name} : ${script_name} failed!${normal}"
      exit ${exit_code}
    fi
  done
fi

exit 0
