name: CMWL Pipeline CI

on:
  pull_request:
    branches:
      - develop
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v2

      - name: Setup Java and Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.11

      - name: Scalafmt Scalastyle check
        run: sbt check scalastyle

      - name: Check dependencies
        run: sbt clean compile undeclaredCompileDependenciesTest

      - name: Run tests
        run: sbt coverage test coverage it:test coverageReport

      - name: Upload coverage data to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}


